# Generated by Django 4.2.1 on 2023-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_car_gear_alter_customer_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='TC_No',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
