# Generated by Django 4.2.1 on 2023-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_car_gear_alter_customer_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Manuel 4 Vites'), (5, 'Manuel 5 Vites'), (6, 'Manuel 6 Vites'), (7, 'Manuel 7 Vites'), (8, 'Manuel 8 Vites'), (1, 'Tam Otomatik Vites'), (2, 'Yarı Otomatik Vites')], default=1),
            preserve_default=False,
        ),
    ]
